branch_whitelist = [ "main" ]
ignore_merge_commits = true
pre_bump_hooks = [
    "cargo test",
    "cargo clippy",
    "cargo fmt --all",
    "cargo set-version {{version}}",
    "cargo build --release",
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
    "cargo package",
    "cargo publish"
]
tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "wr"
owner = "aeyoll"
authors = [
    { signature = "Jean-Philippe Bidegain", username = "aeyoll" },
]
